services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_ICON_URL=URL_HERE
      - SERVER_ADDRESS=ADDRESS
      - SERVER_PORT=PORT
      - SERVER_BOOKMARK=ADDRESS
      # - SERVER_PASSWORD=
      # - JOIN_CHANNEL=
      # - JOIN_CHANNEL_PASSWORD=
      # - TOKEN=
      - FAVICON=URL_HERE